apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: dev
data:
  index.html: |
    <html>
    <body style="background-color: pink;">
    <h1>DEV</h1>
    </body>
    </html