apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: prod
data:
  index.html: |
    <html>
    <body style="background-color: green;">
    <h1>PROD</h1>
    </body>
    </html